project_id = "spqakoyhyziuxfgdkgpm"

[functions.calculate-daily-scores]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.remind-clock-out]
verify_jwt = false

[functions.p2h-toolbox-export]
verify_jwt = false

[functions.time-sync]
verify_jwt = false
