version: '3.8'
services:
  app:
    build: .
    container_name: smart-absensi-app
    ports:
      - "6890:6890"
    environment:
      - PORT=6890
    restart: unless-stopped
    env_file:
      - .env